apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: client-intents-for-client
  namespace: otterize-tutorial-mapper
spec:
  workload:
    name: client
#     kind: Deployment # Not allowed in strict mode
  targets:
    # Intents for the non-Service targets are not supported in strict mode
    - internet:
        domains:
          - google.com
        ports:
          - 80
    - kubernetes:
#         name: client2 # Not allowed in strict mode
#         kind: Deployment # Not allowed in strict mode
    - service:
        name: server