apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: client-intents-for-client
  namespace: otterize-tutorial-mapper
spec:
  workload:
    name: client
    kind: Deployment
  targets:
    - internet:
        domains:
          - google.com
