apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: client-intents-for-client2
  namespace: otterize-tutorial-mapper
spec:
  workload:
    name: client2
    kind: Deployment
  targets:
    - service:
        name: server
    - internet:
        domains:
          - xkcd.com
