apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: client-intents-for-client
  namespace: otterize-tutorial-mapper
spec:
  workload:
    name: client
    kind: Deployment
  targets:
    # Intents for the non-Service targets are not supported in strict mode
    - service:
        name: server
    - internet:
        domains:
          - google.com
        ports:
          - 80
