apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: client-intents-for-client
  namespace: otterize-tutorial-mapper
spec:
  workload:
    name: client
    kind: Deployment
  targets:
    # Intents for the non-Service targets are not supported in strict mode
#     - internet:
#         domains:
#           - google.com
#     - kubernetes:
#         name: client2
#         kind: Deployment
    - service:
        name: server
# Calls to targets other than service are not allowed in strict mode
# Internet calls to domains or IPs without specifying ports are not allowed in strict mode
#     - kubernetes:
#         name: client2
#         kind: Deployment
    - internet:
        domains:
            - google.com
        ports:
            - 80
# Calls to targets other than service are not allowed in strict mode